# Generated by Django 3.1 on 2020-09-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('RESIDENT', 'Resident'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin')], default='RESIDENT', max_length=50)),
            ],
            options={
                'db_table': 'treeckle_user_invite_tab',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_party_authenticator',
            field=models.CharField(choices=[('NONE', 'None'), ('GOOGLE', 'Google'), ('NUSNET', 'Nusnet')], default='NONE', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('third_party_id', 'third_party_authenticator'), name='unique third party id and authenticator'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeckle.organisation'),
        ),
    ]
