# Generated by Django 3.1 on 2020-09-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0002_auto_20200916_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='contact',
        ),
    ]
