# Generated by Django 3.1 on 2020-09-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0004_auto_20200919_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treeckle.organisation'),
            preserve_default=False,
        ),
    ]
