# Generated by Django 3.1 on 2020-09-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0005_venue_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
