# Generated by Django 3.1 on 2020-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0007_auto_20201006_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='isGloballyVisible',
        ),
    ]
