# Generated by Django 3.1 on 2020-10-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0008_auto_20201014_1619'),
        ('treeckle', '0008_auto_20201006_1450'),
    ]

    operations = [
    ]
