# Generated by Django 3.1 on 2020-10-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0008_auto_20201014_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeckle.organisation')),
            ],
            options={
                'db_table': 'venue_category_tab',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treeckle.venuecategory'),
        ),
        migrations.AddConstraint(
            model_name='venuecategory',
            constraint=models.UniqueConstraint(fields=('name', 'organisation_id'), name='unique organisation and venue category name'),
        ),
    ]
