# Generated by Django 3.1 on 2020-10-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0009_auto_20201016_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeckle.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeckle.user')),
            ],
            options={
                'db_table': 'event_subscription_tab',
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('category_id', 'user_id'), name='unique user category subscription'),
        ),
    ]
