# Generated by Django 3.1 on 2020-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0010_auto_20201016_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_filename',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
