# Generated by Django 3.1 on 2020-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0011_event_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='event',
            name='image_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organised_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(max_length=255),
        ),
    ]
