# Generated by Django 3.1 on 2020-10-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0011_event_image_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treeckle.organisation')),
            ],
            options={
                'db_table': 'organisation_listener_tab',
            },
        ),
        migrations.AddConstraint(
            model_name='organisationlistener',
            constraint=models.UniqueConstraint(fields=('email', 'organisation_id'), name='unique organisation and email for listener'),
        ),
    ]
