# Generated by Django 3.1 on 2020-11-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeckle', '0012_auto_20201029_0922'),
        ('treeckle', '0009_merge_20201015_1444'),
        ('treeckle', '0012_auto_20201029_0639'),
    ]

    operations = [
    ]
